### ISSUE TITLE
ResolvePackageNotFound on Windows 

### ISSUE THREAD

**Issue by Renaldas111** [autonomousvision/stylegan_xl#10]
As I read, all these not found packages should go under pip section with different formatting, it is some kind of a bug, I understand (https://github.com/datitran/object_detector_app/issues/41). This would be very time consuming to rename and reformat all these packages manually. Is there a way to make a requirements file for all platforms?

conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - setuptools==52.0.0=py37h06a4308_0
  - cudatoolkit==11.0.221=h6bb024c_0
  - nbconvert==6.1.0=py37h89c1867_0
  - zeromq==4.3.4=h2531618_0
  - jpeg==9b=h024ee3a_2
  - jupyter_core==4.7.1=py37h89c1867_0
  - mistune==0.8.4=py37h4abf009_1002
  - lz4-c==1.9.3=h2531618_0
  - libprotobuf==3.13.0.1=h8b12597_0
  - readline==8.1=h27cfd23_0
  - argon2-cffi==20.1.0=py37h4abf009_2
  - libpng==1.6.37=hbc83047_0
  - jedi==0.18.0=py37h89c1867_2
  - libstdcxx-ng==9.1.0=hdf63c60_0
  - yaml==0.2.5=h516909a_0
  - numpy==1.20.2=py37h2d18471_0
  - cryptography==3.1.1=py37h1ba5d50_0
  - jupyter_nbextensions_configurator==0.4.1=py37h89c1867_2
  - libuv==1.40.0=h7b6447c_0
  - brotlipy==0.7.0=py37h7b6447c_1000
  - zstd==1.4.9=haebb681_0
  - libsodium==1.0.18=h36c2ea0_1
  - freetype==2.10.4=h5ab3b9f_0
  - sqlite==3.35.4=hdfb4753_0
  - intel-openmp==2021.2.0=h06a4308_610
  - zlib==1.2.11=h7b6447c_3
  - mkl==2021.2.0=h06a4308_296
  - tk==8.6.10=hbc83047_0
  - python==3.7.10=hdb3f193_0
  - ipython==7.26.0=py37h6531663_0
  - ca-certificates==2021.10.8=ha878542_0
  - watchdog==0.10.4=py37h89c1867_0
  - pytorch==1.7.1=py3.7_cuda11.0.221_cudnn8.0.5_0
  - libtiff==4.1.0=h2733197_1
  - ninja==1.10.2=hff7bd54_1
  - mpi4py==3.0.3=py37hd955b32_1
  - lcms2==2.12=h3be6417_0
  - matplotlib-base==3.3.1=py37h817c723_0
  - pandas==1.1.3=py37he6710b0_0
  - libgfortran4==7.5.0=ha8ba4b0_17
  - pandoc==2.14.1=h7f98852_0
  - mkl-service==2.3.0=py37h27cfd23_1
  - libgcc-ng==9.1.0=hdf63c60_0
  - xz==5.2.5=h7b6447c_0
  - shortuuid==1.0.1=py37h89c1867_4
  - pip==21.1.2=py37h06a4308_0
  - ld_impl_linux-64==2.33.1=h53a641e_7
  - mkl_random==1.2.1=py37ha9443f7_2
  - pyyaml==5.3.1=py37hb5d75c8_1
  - lxml==4.6.3=py37h9120a33_0
  - openmpi==4.0.2=hb1b8bf9_1
  - cffi==1.14.3=py37he30daa8_0
  - libgfortran-ng==7.5.0=ha8ba4b0_17
  - libxml2==2.9.10=hb55368b_3
  - certifi==2021.10.8=py37h89c1867_1
  - numpy-base==1.20.2=py37hfae3a4d_0
  - ncurses==6.2=he6710b0_1
  - openssl==1.1.1n=h7f8727e_0
  - promise==2.3=py37h89c1867_4
  - tornado==6.1=py37h4abf009_0
  - pillow==8.2.0=py37he98fc37_0
  - jupyter_highlight_selected_word==0.2.0=py37h89c1867_1002
  - libxslt==1.1.34=hc22bd24_0
  - kiwisolver==1.3.1=py37hc928c03_0
  - libffi==3.3=he6710b0_2
  - icu==58.2=hf484d3e_1000
  - mkl_fft==1.3.0=py37h42c9631_2

**Comment by xl-sr** [comment]
I added a minimal environment, you can give it a try again

**Comment by Renaldas111** [comment]
Ok, thanks!
This time the environment installs with no problem, but the next problem was AssertionError: Torch not compiled with CUDA enabled. Solved it by  conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch . Remember spending hours and getting the same problem when trying to install Stylegan and ProjectedGAN, so this time solved the problem in minutes. Would be nice if the proper version would be installed straight out of environment file.
Finally, tried to run python train.py --outdir=I:/Out --cfg=stylegan3-t --data=I:/data256.zip --gpus 1 --batch=4 --mirror=1 --snap 10 --kimg 10000 --stem --syn_layers 10 --metrics=none
The process stuck at Setting up PyTorch plugin "filtered_lrelu_plugin"... Maybe I was not patient enough, but waited for more than 5 minutes seemed for me reasonable amount of time to conclude something is wrong.

Finally, I just ran Stylegan XL from ProjectedGAN env I used for many months. It asked for several additional modules to install, and at least now I am at:

Setting up augmentation...
Distributing across 1 GPUs...
Setting up training phases...
Exporting sample images...
Initializing logs...
Skipping tfevents export: No module named 'tensorboard'
Training for 10000 kimg...

Setting up PyTorch plugin "upfirdn2d_plugin"... Done.
tick 0     kimg 0.0      time 2m 08s       sec/tick 12.8    sec/kimg 3199.28 maintenance 115.1  cpumem 4.98   gpumem 6.60   reserved 8.08   augment 0.000

**Comment by xl-sr** [comment]
great that it works for you now :) it's always tricky to make environments work everywhere. I'll leave the environment as is now and close this issue, but I'll refer to it in the README for Windows users.

**Comment by huvers** [comment]
Windows still gave me an issue with 'cudatoolkit=11.1', but adding 'conda-forge' to the channels in environment.yml solves it.

**Comment by rimless** [comment]
> Ok, thanks! This time the environment installs with no problem, but the next problem was AssertionError: Torch not compiled with CUDA enabled. Solved it by conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch . Remember spending hours and getting the same problem when trying to install Stylegan and ProjectedGAN, so this time solved the problem in minutes. Would be nice if the proper version would be installed straight out of environment file. Finally, tried to run python train.py --outdir=I:/Out --cfg=stylegan3-t --data=I:/data256.zip --gpus 1 --batch=4 --mirror=1 --snap 10 --kimg 10000 --stem --syn_layers 10 --metrics=none The process stuck at Setting up PyTorch plugin "filtered_lrelu_plugin"... Maybe I was not patient enough, but waited for more than 5 minutes seemed for me reasonable amount of time to conclude something is wrong.
> 
> Finally, I just ran Stylegan XL from ProjectedGAN env I used for many months. It asked for several additional modules to install, and at least now I am at:
> 
> Setting up augmentation... Distributing across 1 GPUs... Setting up training phases... Exporting sample images... Initializing logs... Skipping tfevents export: No module named 'tensorboard' Training for 10000 kimg...
> 
> Setting up PyTorch plugin "upfirdn2d_plugin"... Done. tick 0 kimg 0.0 time 2m 08s sec/tick 12.8 sec/kimg 3199.28 maintenance 115.1 cpumem 4.98 gpumem 6.60 reserved 8.08 augment 0.000

I met the same problem, and don't know why. It will stuck for 30 mins and quit automatically since the timeout.
