### ISSUE TITLE
Typo in feature_networks/constants.py?

### ISSUE THREAD

**Issue by mehdidc** [autonomousvision/stylegan_xl#14]
Hi, thanks for releasing the code!
shouldn't https://github.com/autonomousvision/stylegan_xl/blob/main/feature_networks/constants.py#L104 rather
be `VITS = VITS_IMAGENET + VITS_INCEPTION` ? because I have the assertion at https://github.com/autonomousvision/stylegan_xl/blob/main/feature_networks/pretrained_builder.py#L196 which is raised when I try to run the training.

**Comment by woctezuma** [comment]
Correct.

https://github.com/autonomousvision/stylegan_xl/blob/d7ddbe74e8141d70779f38a38ab94bc23bed8bf5/feature_networks/constants.py#L94-L104

**Comment by xl-sr** [comment]
thanks, fixed
