### ISSUE TITLE
unexpected arguments to MetricOptions constructor

### ISSUE THREAD

**Issue by v-shmyhlo** [autonomousvision/stylegan_xl#18]
`metric_main.calc_metric` is called with `run_dir` and `cur_nimg` which are then forwarded to `metric_utils.MetricOptions` which doesn't expect those arguments in constructor - running example training scripts raises unexpected argument error.
https://github.com/autonomousvision/stylegan_xl/blob/main/training/training_loop.py#L477-L478
https://github.com/autonomousvision/stylegan_xl/blob/main/metrics/metric_utils.py#L35

**Comment by woctezuma** [comment]
True. One should remove the unexpected arguments from:

https://github.com/autonomousvision/stylegan_xl/blob/0790fac3eea43c4995d151ba63b5b9e2240f4db0/training/training_loop.py#L477-L478

**Comment by xl-sr** [comment]
fixed, thanks
