### ISSUE TITLE
code and pretrained models 

### ISSUE THREAD

**Issue by betterze** [autonomousvision/stylegan_xl#2]
Dear StyleGAN_xl team,

Thank you for your great work. The results are amazing.

Do you have plan to release the code and pretrained models? When you will release them? 

Thank you for your help.

Best Wishes,

Zongze

**Comment by xl-sr** [comment]
Hi, thanks for the kind words :) The full code release, including all pretrained models, is planned for the end of March.

**Comment by betterze** [comment]
The codes will be released in a few days, right? Thank you for your help.

**Comment by xl-sr** [comment]
yes

**Comment by 19Ply3** [comment]
Hi there does stylegan xl allows you to use your own pictures

**Comment by Youzebin** [comment]
The codes will be released in today, right? Thank you for your help.

**Comment by woctezuma** [comment]
- aa6531372d3517cfe3157631093191e8cfea2aaf
