### ISSUE TITLE
Hello, may I ask you how much data you used in your Pokemon image generation project

### ISSUE THREAD

**Issue by jexz11** [autonomousvision/stylegan_xl#20]
Hello, may I apply to you for sharing the data set of POKEMON? I've been working on a Pokemon image generation project recently, but the quality of the generated Pokemon is so poor (FID93) that they are like Cthulhu growling

**Comment by jexz11** [comment]
![P }I029AGU%KXRGG)Z`O TI](https://user-images.githubusercontent.com/76417800/161991246-7f579767-dd26-4a75-b847-4bcff7d9e7eb.png)

**Comment by xl-sr** [comment]
here you go:
https://drive.google.com/file/d/1aAJCZbXNHyraJ6Mi13dSbe7pTyfPXha0/view

**Comment by jexz11** [comment]
Thanks for your reply ~~

**Comment by jexz11** [comment]
Can I ask your parameter setting + training times? I'd like to try to reproduce the model if it doesn't take much time❤

**Comment by jexz11** [comment]
However, my GPU is only 2GB, I see your readme file, the video memory of my computer does not support training, so I need to rent Google Cloud.For this reason, I really want to refer to your training parameters and training time

**Comment by jexz11** [comment]
Ok, sorry for not reading your README carefully, sorry to disturb you ~❤

**Comment by xl-sr** [comment]
no worries :)
