### ISSUE TITLE
Possible Metrics Issues

### ISSUE THREAD

**Issue by taconugget** [autonomousvision/stylegan_xl#22]
Training works great however when it gets to calculating metrics I receive the following errors.

`Calculating the stats for this dataset the first time

Saving them to ./dnnlib/gan-metrics/Solitude16-inception-2015-12-05-d3fec46f71c9675575ac92ce317e7832.pkl
/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 3 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
  0%|          | 0/69 [00:00<?, ?it/s]
  1%|1         | 1/69 [00:19<22:37, 19.96s/it]
  3%|2         | 2/69 [00:20<09:20,  8.37s/it]
  4%|4         | 3/69 [00:20<05:04,  4.61s/it]
  6%|5         | 4/69 [00:22<03:54,  3.60s/it]
  7%|7         | 5/69 [00:22<02:31,  2.37s/it]
  9%|8         | 6/69 [00:22<01:41,  1.61s/it]
 10%|#         | 7/69 [00:22<01:10,  1.14s/it]
 12%|#1        | 8/69 [00:23<00:49,  1.23it/s]
 13%|#3        | 9/69 [00:23<00:36,  1.66it/s]
 14%|#4        | 10/69 [00:23<00:27,  2.18it/s]
 16%|#5        | 11/69 [00:23<00:20,  2.80it/s]
 17%|#7        | 12/69 [00:23<00:16,  3.48it/s]
 19%|#8        | 13/69 [00:23<00:13,  4.16it/s]
 20%|##        | 14/69 [00:23<00:11,  4.79it/s]
 22%|##1       | 15/69 [00:23<00:09,  5.43it/s]
 23%|##3       | 16/69 [00:24<00:08,  6.01it/s]
 25%|##4       | 17/69 [00:24<00:08,  6.41it/s]
 26%|##6       | 18/69 [00:24<00:07,  6.81it/s]
 28%|##7       | 19/69 [00:24<00:07,  7.12it/s]
 29%|##8       | 20/69 [00:24<00:06,  7.20it/s]
 30%|###       | 21/69 [00:24<00:06,  7.41it/s]
 32%|###1      | 22/69 [00:24<00:06,  7.33it/s]
 33%|###3      | 23/69 [00:24<00:06,  7.39it/s]
 35%|###4      | 24/69 [00:25<00:05,  7.51it/s]
 36%|###6      | 25/69 [00:25<00:05,  7.67it/s]
 38%|###7      | 26/69 [00:25<00:05,  7.69it/s]
 39%|###9      | 27/69 [00:25<00:05,  7.60it/s]
 41%|####      | 28/69 [00:25<00:05,  7.00it/s]
 42%|####2     | 29/69 [00:25<00:06,  6.51it/s]
 43%|####3     | 30/69 [00:25<00:05,  6.64it/s]
 45%|####4     | 31/69 [00:26<00:05,  7.01it/s]
 46%|####6     | 32/69 [00:26<00:05,  7.36it/s]
 48%|####7     | 33/69 [00:26<00:04,  7.65it/s]
 49%|####9     | 34/69 [00:26<00:04,  7.19it/s]
 51%|#####     | 35/69 [00:26<00:04,  7.51it/s]
 52%|#####2    | 36/69 [00:26<00:04,  7.57it/s]
 54%|#####3    | 37/69 [00:26<00:04,  7.24it/s]
 55%|#####5    | 38/69 [00:27<00:04,  7.36it/s]
 57%|#####6    | 39/69 [00:27<00:04,  7.42it/s]
 58%|#####7    | 40/69 [00:27<00:03,  7.58it/s]
 59%|#####9    | 41/69 [00:27<00:03,  7.54it/s]
 61%|######    | 42/69 [00:27<00:03,  7.49it/s]
 62%|######2   | 43/69 [00:27<00:03,  7.61it/s]
 64%|######3   | 44/69 [00:27<00:03,  7.70it/s]
 65%|######5   | 45/69 [00:27<00:03,  7.80it/s]
 67%|######6   | 46/69 [00:28<00:03,  7.54it/s]
 68%|######8   | 47/69 [00:28<00:02,  7.54it/s]
 70%|######9   | 48/69 [00:28<00:02,  7.57it/s]
 71%|#######1  | 49/69 [00:28<00:02,  7.45it/s]
 72%|#######2  | 50/69 [00:28<00:02,  7.38it/s]
 74%|#######3  | 51/69 [00:28<00:02,  7.32it/s]
 75%|#######5  | 52/69 [00:28<00:02,  6.98it/s]
 77%|#######6  | 53/69 [00:29<00:02,  7.25it/s]
 78%|#######8  | 54/69 [00:29<00:02,  7.16it/s]
 80%|#######9  | 55/69 [00:29<00:01,  7.42it/s]
 81%|########1 | 56/69 [00:29<00:01,  7.54it/s]
 83%|########2 | 57/69 [00:29<00:01,  7.67it/s]
 84%|########4 | 58/69 [00:29<00:01,  7.76it/s]
 86%|########5 | 59/69 [00:29<00:01,  7.80it/s]
 87%|########6 | 60/69 [00:29<00:01,  7.57it/s]
 88%|########8 | 61/69 [00:30<00:01,  7.54it/s]
 90%|########9 | 62/69 [00:30<00:00,  7.60it/s]
 91%|#########1| 63/69 [00:30<00:00,  7.75it/s]
 93%|#########2| 64/69 [00:30<00:00,  8.03it/s]
 94%|#########4| 65/69 [00:30<00:00,  8.23it/s]
 96%|#########5| 66/69 [00:30<00:00,  8.27it/s]
 97%|#########7| 67/69 [00:30<00:00,  8.36it/s]
 99%|#########8| 68/69 [00:30<00:00,  8.14it/s]
100%|##########| 69/69 [00:31<00:00,  3.60it/s]
100%|##########| 69/69 [00:32<00:00,  2.10it/s]
Traceback (most recent call last):
  File "/content/drive/.shortcut-targets-by-id/1f-kIJloZwicV2WXZYcNGGXmZ9dyxIaeO/colab-sg3XL/stylegan_xl/dnnlib/util.py", line 45, in __getattr__
    return self[name]
KeyError: 'truncation_psi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 332, in <module>
    main()  # pylint: disable=no-value-for-parameter
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "train.py", line 317, in main
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)
  File "train.py", line 104, in launch_training
    subprocess_fn(rank=0, c=c, temp_dir=temp_dir)
  File "train.py", line 49, in subprocess_fn
    training_loop.training_loop(rank=rank, **c)
  File "/content/drive/.shortcut-targets-by-id/1f-kIJloZwicV2WXZYcNGGXmZ9dyxIaeO/colab-sg3XL/stylegan_xl/training/training_loop.py", line 478, in training_loop
    dataset_kwargs=training_set_kwargs, num_gpus=num_gpus, rank=rank, device=device)
  File "/content/drive/.shortcut-targets-by-id/1f-kIJloZwicV2WXZYcNGGXmZ9dyxIaeO/colab-sg3XL/stylegan_xl/metrics/metric_main.py", line 43, in calc_metric
    results = _metric_dict[metric](opts)
  File "/content/drive/.shortcut-targets-by-id/1f-kIJloZwicV2WXZYcNGGXmZ9dyxIaeO/colab-sg3XL/stylegan_xl/metrics/metric_main.py", line 83, in fid50k_full
    fid = frechet_inception_distance.compute_fid(opts, max_real=None, num_gen=50000)
  File "/content/drive/.shortcut-targets-by-id/1f-kIJloZwicV2WXZYcNGGXmZ9dyxIaeO/colab-sg3XL/stylegan_xl/metrics/frechet_inception_distance.py", line 35, in compute_fid
    rel_lo=0, rel_hi=1, capture_mean_cov=True, max_items=num_gen, sfid=sfid).get_mean_cov()
  File "/content/drive/.shortcut-targets-by-id/1f-kIJloZwicV2WXZYcNGGXmZ9dyxIaeO/colab-sg3XL/stylegan_xl/metrics/metric_utils.py", line 331, in compute_feature_stats_for_generator
    w = gen_utils.get_w_from_seed(G, batch_gen, opts.device, truncation_psi=opts.G_kwargs.truncation_psi,
  File "/content/drive/.shortcut-targets-by-id/1f-kIJloZwicV2WXZYcNGGXmZ9dyxIaeO/colab-sg3XL/stylegan_xl/dnnlib/util.py", line 47, in __getattr__
    raise AttributeError(name)
AttributeError: truncation_psi`

**Comment by xl-sr** [comment]
fixed, thanks

**Comment by taconugget** [comment]
thank you sir!
