### ISSUE TITLE
Not an issue - why new StyleganXL -t is so "heavy"?

### ISSUE THREAD

**Issue by Renaldas111** [autonomousvision/stylegan_xl#24]
What is the difference between Stylegan3-r and t generators and StyleganXL-r and t generators? In Stylegan3 both were comparable in speed (+-50 %) of training using the same parameters, in StyleganXL the -t is like 5+ times slower in training in comparison to -r. Is it normal? Also noticed StyleganXL -t generator has something like 80M parameters, when -r has about 20M (Stylegan3 both -t and -r had 20-30M) (trying to write the figures from memory).

**Comment by xl-sr** [comment]
Actually, the models are this heavy. There is a small bug in the config-r specification currently, it should have double the parameters than it has right now.

If you want to train lighter models, see "Training recommendations for datasets other than ImageNet" in the README.
