### ISSUE TITLE
Not resize image to 224 for the ViT-based discriminator

### ISSUE THREAD

**Issue by htzheng** [autonomousvision/stylegan_xl#27]
https://github.com/autonomousvision/stylegan_xl/blob/819c225e7fd60114cde0bad79f3cb5a4ba8621cd/pg_modules/discriminator.py#L180

Thank you for the great work! I noticed that in pg_modules/discriminator.py,  there is a line `bb_name += f"_{i}" that will make bb_name from "deit_base_distilled_patch16_224" to "deit_base_distilled_patch16_224_0". Then in the forward pass, the input image will not be resized to 244 for the ViT model. Not sure if that is intentional or the image should be resized to 224 (especially for higher resolution such as 512x512 or 1024x1024)

Thanks again!

**Comment by woctezuma** [comment]
I think interpolation happens for this reason, no?

https://github.com/autonomousvision/stylegan_xl/blob/819c225e7fd60114cde0bad79f3cb5a4ba8621cd/pg_modules/discriminator.py#L201-L202

**Comment by xl-sr** [comment]
that is a bug, it should downsize to 224 for ViTs.
Fixed it, thanks! :slightly_smiling_face:

**Comment by xl-sr** [comment]
unsuccessfully though :sweat_smile: 

```bb_name += f"_{i}``` lead to https://github.com/autonomousvision/stylegan_xl/commit/6957917e5042f5710c1a10b3df56cca70e4432fe being ignored.
