### ISSUE TITLE
Non-saturating loss or least-square GAN loss

### ISSUE THREAD

**Issue by htzheng** [autonomousvision/stylegan_xl#28]
I noticed that the discriminator loss is the least-square GAN loss rather than the non-saturating loss of StyleGAN3, I wonder if the least-square GAN loss can achieve better results and where I could find the discussion on the GAN loss in the paper. Thank you a lot!

**Comment by xl-sr** [comment]
It's a hinge loss ([Geometric GAN](https://arxiv.org/abs/1705.02894)). We also used this in "Projected GANs Converge Faster". In my experience, there is little difference between different losses, especially for Projected GANs.

**Comment by htzheng** [comment]
Thanks! I appreciate the quick reply!
