### ISSUE TITLE
README: wrong link to class-labels

### ISSUE THREAD

**Issue by woctezuma** [autonomousvision/stylegan_xl#29]
In the section [Generating Samples & Interpolations](https://github.com/autonomousvision/stylegan_xl#generating-samples--interpolations) of the README, a link is wrong.

> For class-conditional models, you can pass the class index via --class.
> A index-to-label dictionary for Imagenet can be found [here](https://github.com/xl-sr/stylegan_xl_release/blob/main/media/imagenet_idx2labels.txt).

As you can see the last link leads to a non-existing repository.

The link should be:
> https://github.com/autonomousvision/stylegan_xl/blob/main/media/imagenet_idx2labels.txt

**Comment by xl-sr** [comment]
thx, fixed
