### ISSUE TITLE
Hello, I want to run your pre-training model on CoLab, but there is this problem 

### ISSUE THREAD

**Issue by jexz11** [autonomousvision/stylegan_xl#33]
Hello, I want to run your pre-training model on CoLab, but there is this problem in the middle, what should I do?
<img width="467" alt="1650266745(1)" src="https://user-images.githubusercontent.com/76417800/163772862-50c58277-586c-4c54-a551-0c4d131d7e16.png">

**Comment by woctezuma** [comment]
Maybe linked to the HTTP error `416 Range Not Satisfiable`.

**Comment by xl-sr** [comment]
the Pokemon models is unconditional, hence ```G.c_dim=0```. As second input to the mapping network, you can just pass ```None```.
