### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by Youzebin** [autonomousvision/stylegan_xl#34]
when i try to train your great project, something wrong. do you know the reason for RuntimeError: No such operator aten::cudnn_convolution_backward_weight??? thank you very much~

**Comment by woctezuma** [comment]
- #23

**Comment by Youzebin** [comment]
> * [Error Running Demo #23](https://github.com/autonomousvision/stylegan_xl/issues/23)

I have another question, you mentioned in your paper that it is best to set the batch_size to 2048 when the resolution is between 16 and 64, but when I set the batch_size to 32, 2 gpu's and a separate batch_size of 16, it already shows that a single GPU with 16 video memory is not enough.
Is it possible that the batch_size you mentioned in your paper requires too much video memory?
@woctezuma

**Comment by xl-sr** [comment]
so you managed to solve your problem above?

**Comment by woctezuma** [comment]
> Is it possible that the batch_size you mentioned in your paper requires too much video memory?

I am not an author of the paper.

By the way, if the issue is solved, feel free to create another issue for the new one.

**Comment by Youzebin** [comment]
> so you managed to solve your problem above?

yes.  I do some experiment to solve this problem. 
when i use pytorch1.7.1, i solve the above problem.
