### ISSUE TITLE
imagenet_centroids

### ISSUE THREAD

**Issue by betterze** [autonomousvision/stylegan_xl#35]
Dear stylegan_xl group, 

Thank you for sharing this great work, I really like it. 

If I understand correctly, the imagenet_centroids in this [link](https://s3.eu-central-1.amazonaws.com/avg-projects/stylegan_xl/models/imagenet_centroids.npy) is only for resolution 128, is this correct? If so, could you share the imagenet_centroids for other resolutions?

Thank you for your help.

Best Wishes,

Zongze

**Comment by xl-sr** [comment]
the imagenet_centroids are the same across resolutions, the mapping network is not trained after the initial stage :)
