### ISSUE TITLE
adaptive discriminator augmentation?

### ISSUE THREAD

**Issue by mspiegel** [autonomousvision/stylegan_xl#37]
Does stylegan_xl work with the `AugmentPipe` step? Looks like the pipeline step is checked in to the repository (https://github.com/autonomousvision/stylegan_xl/blob/main/training/augment.py) but it has been removed from the command-line options. Wondering if you'd had a chance to play with it?

**Comment by xl-sr** [comment]
Yes, we compared ADA and Diffaug in [Projected GANs Converge Faster](https://github.com/autonomousvision/projected_gan), and Projected GANs (which SGXL is using) do not seem to profit from the adaptivity. :)

**Comment by mspiegel** [comment]
Thank you for the feedback!
