### ISSUE TITLE
How to train next super-resolution stage

### ISSUE THREAD

**Issue by mspiegel** [autonomousvision/stylegan_xl#38]
Hi,

I might be a bit dense but I'm not sure how to train the second super-resolution stage once I have completed training the first super-resolution stage. Taking the pokemon dataset example from the README.md if I start with:

```
python train.py --outdir=./training-runs/pokemon --cfg=stylegan3-t --data=./data/pokemon16.zip \
    --gpus=8 --batch=64 --mirror=1 --snap 10 --batch-gpu 8 --kimg 10000 --syn_layers 10
```

And then train

```
python train.py --outdir=./training-runs/pokemon --cfg=stylegan3-t --data=./data/pokemon32.zip \
  --gpus=8 --batch=64 --mirror=1 --snap 10 --batch-gpu 8 --kimg 10000 --syn_layers 10 \
  --superres --up_factor 2 --head_layers 7 \
  --path_stem training-runs/pokemon/00000-stylegan3-t-pokemon16-gpus8-batch64/best_model.pkl
```

Now how do I train the 64x64 model from the 32x32 model? Is the next path stem `training-runs/pokemon/00001-stylegan3-t-pokemon32-gpus8-batch64/best_model.pkl` from the 32x32 model or is it from the original 16x16 model? Is the next syn_layers parameter a 10 or a 7?

Thanks in advance.

**Comment by xl-sr** [comment]
Hi :)
The next step would be:
```
python train.py --outdir=./training-runs/pokemon --cfg=stylegan3-t --data=./data/pokemon64.zip \
  --gpus=8 --batch=64 --mirror=1 --snap 10 --batch-gpu 8 --kimg 10000 --syn_layers 10 \
  --superres --up_factor 2 --head_layers 7 \
  --path_stem training-runs/pokemon/00001-stylegan3-t-pokemon32-gpus8-batch64/best_model.pkl
```
```syn_layers``` is maybe a bit misleading, I might rename it to ```stem_layers```. As a tip, for smaller/easier datasets than ImageNet, ```head_layers 4``` is sufficient.
