### ISSUE TITLE
StyleGan2 support

### ISSUE THREAD

**Issue by Hareesh-Ravi** [autonomousvision/stylegan_xl#39]
Hi,

I am trying to train a model with stylegan2 as the base config with class labels.

1. I got a couple of errors
`(TypeError: __init__() got an unexpected keyword argument ‘num_layers’)`
with the kwargs such as:
[c.G_kwargs.num_layers = opts.syn_layers](https://github.com/autonomousvision/stylegan_xl/blob/287f92779ad236728a64b1697d52bee752fccc15/train.py#L272)
[c.G_kwargs.mapping_kwargs.rand_embedding = False](https://github.com/autonomousvision/stylegan_xl/blob/287f92779ad236728a64b1697d52bee752fccc15/train.py#L271)
I was unable to find usage of these kwargs in /training/networks_stylegan2.py. I commented them out and continued to get the following error.

2. Also, the mapping network does not use pretrained class embedding as conditioning in stylegan2.py
[self.embed = FullyConnectedLayer(c_dim, embed_features)](https://github.com/autonomousvision/stylegan_xl/blob/287f92779ad236728a64b1697d52bee752fccc15/training/networks_stylegan2.py#L279). I modified this based on SG3 code but then got the following error in metric calculation.

3. Also, self.w_avg in styleGAN2 mapping network is not label specific and this throws an error in metric calculation while synthesizing label specific w's. 

Am I doing something wrong or there is no support for class conditional training with stylegan2 as the base?

**Comment by xl-sr** [comment]
As of now, SG2 is not supported. It will require some changes and it is not high on my prio. Feel free to submit a PR though if you manage to make it work :)

**Comment by Hareesh-Ravi** [comment]
Sure, thank you for the response. 👍

**Comment by Kim-Dongjun** [comment]
@Hareesh-Ravi

Hi, I wonder if you have succeeded in training styleGAN-XL with the styleGAN2 generator.
