### ISSUE TITLE
how to prepare imagenet dataset

### ISSUE THREAD

**Issue by Youzebin** [autonomousvision/stylegan_xl#40]
hello, thank you for your great work.
I can't find the usage of preparing the imagenet dataset in dataset_tool.py
now, if i have a imagenet zip,  how can i prepare this data.
thank you for your help

**Comment by Youzebin** [comment]
please, i think this is very important

**Comment by xl-sr** [comment]
The steps are:
- download ImageNet: https://www.image-net.org/
- pass through ```dataset_tool.py``` with the center-crop transformation
- prepare labels and add them to the zip. See README: "The dataset needs to contain the class labels; see the [StyleGAN2-ADA repo](https://github.com/NVlabs/stylegan2-ada-pytorch) on how to prepare class-conditional datasets."

**Comment by Youzebin** [comment]
thank you very much
