### ISSUE TITLE
how to prepare imagenet dataset

### ISSUE THREAD

**Issue by yuxuany1** [autonomousvision/stylegan_xl#43]
Hello, your project mentions the use of imagenet dataset, but I have some problems in reproducing it, because there is no usage method for imagenet dataset in datatool.
Also, I would like to know how to effectively train the sota results you mentioned in paperswithcode, do you have your training plan? For example, what settings are used for training 16, 32, 64 stages, which are usually written in the yaml file, and how much time it takes to train Imagenet with these settings, if v100/day is used
It may be a bit long.

**Comment by Youzebin** [comment]
#40

**Comment by xl-sr** [comment]
- Regarding data preparation, see the issue above.
- The examples in the README are the standard settings for training on ImageNet.
- As we write in the paper, training takes ~400 V100-days, so yeah, it is a bit long :grin:

**Comment by Youzebin** [comment]
I have another question, what is the number of kimg required for each stage of convergence, such as tem16, 16->32, 32->64, 64->128, 128->256, how many resolutions do you mean by 400 v100-days, is it from tem to 1024, it looks like 400 v100-days is not that long. It doesn't look that long.
Also I would like to know how to get the results of each stage, is it up-factor 2 at each step and then generate step by step, or is it up-factor=4 at early stage and directly from 16->64, thank you.

> * As we write in the paper, training takes ~400 V100-days, so yeah, it is a bit long 😁

**Comment by yuxuany1** [comment]
> * Regarding data preparation, see the issue above.
> * The examples in the README are the standard settings for training on ImageNet.
> * As we write in the paper, training takes ~400 V100-days, so yeah, it is a bit long 😁

Hi, I don't see how to prepare the class conditional dataset in stylegan2-ada ah, only how to prepare cifar10, it doesn't say how to prepare the tag data into zip

**Comment by yuxuany1** [comment]
Thank you very much for your detailed answer.
