### ISSUE TITLE
What if Efficientnet-lite1 and DeiT are combined?

### ISSUE THREAD

**Issue by htzheng** [autonomousvision/stylegan_xl#45]
In Table 2 of the projected-gan paper, I noticed that Efficientnet-lite1 achieves the best FID, I wonder what would happen if Efficientnet-lite1 and DeiT are jointly used as the stylegan-xl discriminators - will it improve the performance? Thank you a lot!

**Comment by xl-sr** [comment]
It won't. On ImageNet it did not make a difference, so we chose the (slightly) faster Effnet-lite0 over Effnet-lite1 :)
