### ISSUE TITLE
encoder for stylegn-xl

### ISSUE THREAD

**Issue by betterze** [autonomousvision/stylegan_xl#48]
Dear stlegan-xl group,

Thank you for sharing this great work, i really like it.

Have you try to train an encoder for the stylegan xl model pretrained on imagenet? Maybe the psp or the e4e encoder?

Thank you for your help.

Best Wishes,

Zongze

**Comment by betterze** [comment]
Instead of using PTI for imge inversion, is there possible to train an encoder to do this?

**Comment by xl-sr** [comment]
hey 🙂 it is of course possible, i haven't done it though. However, it should be straightforward to modify and use the [e4e repo](https://github.com/omertov/encoder4editing) for this purpose.

**Comment by betterze** [comment]
Thx a lot.
