### ISSUE TITLE
why clip produces bad results

### ISSUE THREAD

**Issue by eliohead** [autonomousvision/stylegan_xl#50]
To my knowledge, Clip is used to find the image that most closely matches the one described in the prompt in the latent space of the neural network. So I can not understand why when I type "a yellow tiger"  on Stylegan XL + Clip this is what colab gives me back: 
![download](https://user-images.githubusercontent.com/51296679/168445448-b48d0fba-174d-429f-9d19-b621e89ff555.png)
Doesn't Imagenet have a class for tigers? It shouldn't generate it any better? Even when I write "a cat", it gives me this result back.
 It sure doesn't look like a cat.
![download (1)](https://user-images.githubusercontent.com/51296679/168445466-39a45f86-9eca-4625-9eb4-95baed7d206c.png)
Am I missing something or there is an explanation to these results not being of better quality like the ones obtained by sampling?

**Comment by xl-sr** [comment]
This is mostly due to initialization and optimization. The network can definitely produce realistic-looking tigers, but the notebook is not tuned for this.
