### ISSUE TITLE
About Colab

### ISSUE THREAD

**Issue by MontaEllis** [autonomousvision/stylegan_xl#51]
Nice work! Could you please release Colab code? I want to have a try.

**Comment by rocks2021** [comment]
Do you want to try mine? I've been training in Colab and got FID=49. Then the Colab stopped. I'm right now trying to figure out how to resume training because I got an attributeerror msg.

**Comment by xl-sr** [comment]
Hey :) I do not plan on setting one up but it should be straightforward to do. I have also seen some floating around elsewhere so you might want to google it first.
