### ISSUE TITLE
Replicate video demo results: transition from Chimpanzees to Human face

### ISSUE THREAD

**Issue by wuqiuche** [autonomousvision/stylegan_xl#54]
Hello,

Thank you for sharing this great work!

I am particularly wondering how to replicate the video demo shown in the twitter (https://twitter.com/autovisiongroup/status/1522533826324578304?s=21&t=6c_FXyqAbXGUecPlDZMQVQ). Specifically, between 0:11 and 0:16, the video shows a transition from Chimpanzees to Human face.

I realize the code to generate a video has already been released, but to generate such transition, I assume we need a GAN that trained on both Chimpanzees and Human face. I guess Chimpanzees is from Imagenet and Humanface is from FFHQ. Do we have such a GAN model that can generate FFHQ face and Imagenet face simultaneously?

Thank you very much, and looking forward to hearing from you.

**Comment by xl-sr** [comment]
For this video i stiched together the ImageNet and the FFHQ model. The transition is done via PTI of one of the models (see ```run_inversion.py```).
