### ISSUE TITLE
When trying to resume training, I got AttributeError: 'VisionTransformer' object has no attribute 'forward_flex'.

### ISSUE THREAD

**Issue by rocks2021** [autonomousvision/stylegan_xl#55]
Any tips or suggestions will be greatly appreciated. Thanks.

**Comment by liyourk** [comment]
same issue to me.

**Comment by liyourk** [comment]
same issue to me. btw, are you using that in colab?

**Comment by taconugget** [comment]
same issue here. using colab.

**Comment by woctezuma** [comment]
Maybe related:
- #56

**Comment by dvschultz** [comment]
+1. Nothing has changed in the repo so I assume it might be something in updated pip dependencies on Colab. Tried rolling pytorch back and that didn’t help.

**Comment by taconugget** [comment]
Not my fix this came from Simon above. I havnt tested it fully but it appears to be working:

!pip install timm==0.4.12 ftfy==6.1.1 ninja==1.10.2 numpy==1.20 click==8.0 pillow==8.3.1 scipy==1.7.1 requests==2.26.0 tqdm==4.62.2 matplotlib==3.4.2 \
imageio==2.9.0 dill==0.3.4 psutil==5.8.0 regex==2022.3.15 imgui==1.3.0 glfw==2.2.0 pyopengl==3.1.5 imageio-ffmpeg==0.4.3 pyspng opensimplex

and then:
!pip uninstall torch torchvision -y
!pip install torch==1.9.1+cu111 torchvision==0.10.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by rocks2021** [comment]
Thank you, taconugget!
However, it is still not working on my Colab.

**Comment by taconugget** [comment]
Make sure to restart the runtime after the install and also revert back one version of your PKL in Google drive before the error happened. Works for Simon and myself after doing so.

**Comment by rocks2021** [comment]
What do you mean by saying "revert back one version of PKL"? As far as I know, the projectedGAN only saves the best_model.pkl and the last pkl file, right? Thanks.

**Comment by taconugget** [comment]
Use Google drive web app to restore a previous version of your pkl before it became broken. I'm away from a computer currently and won't be back till Monday so I can't rember the exact terms used, but Google drive allows restoring of older versions of files in its history.

**Comment by rocks2021** [comment]
I see. Thanks.

**Comment by taconugget** [comment]
Gluck hope it works for you!

**Comment by taconugget** [comment]
Right click the file in Google drive and click "Manage Versions" here you can restore a previous version of the PKL.

**Comment by rocks2021** [comment]
Thank you very much, taconugget! Yup, I understand what you said. I actually trained the model by installing the older version of PyTorch and also the dependencies even before getting the error when trying to resume. Then I followed all your instructions: I restarted the runtime and also used a previous version of PKL. Still, the same AttributeError shows up again and again.

**Comment by dvschultz** [comment]
> Not my fix this came from Simon above. I havnt tested it fully but it appears to be working:
> 
> !pip install timm==0.4.12 ftfy==6.1.1 ninja==1.10.2 numpy==1.20 click==8.0 pillow==8.3.1 scipy==1.7.1 requests==2.26.0 tqdm==4.62.2 matplotlib==3.4.2 imageio==2.9.0 dill==0.3.4 psutil==5.8.0 regex==2022.3.15 imgui==1.3.0 glfw==2.2.0 pyopengl==3.1.5 imageio-ffmpeg==0.4.3 pyspng opensimplex
> 
> and then: !pip uninstall torch torchvision -y !pip install torch==1.9.1+cu111 torchvision==0.10.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html

This worked for me. In some cases I had to restart my models from the 16x16 version. Unsure exactly when this update took place so I did lose a few days of training :/

**Comment by rocks2021** [comment]
It's working now. Thanks.

**Comment by nicholasjprimianomd** [comment]
The fixes above are not working on Ubuntu 22.04. I get the same error saving the model at the end of training.

**Comment by ryan-cranfill** [comment]
Had this issue trying to resume training on a model as well. Got training working again by applying this monkey patch in `feature_networks/vit.py` (in a similar fashion to how it's already being done in the `_make_*_backbone` functions).

```python
# Monkeypatching the VisionTransformer class to make it work when resuming training
from timm.models.vision_transformer import VisionTransformer
VisionTransformer.forward_flex = types.MethodType(forward_flex, VisionTransformer)
VisionTransformer._resize_pos_embed = types.MethodType(_resize_pos_embed, VisionTransformer)
```
I added this just after the def of `forward_flex`, around line 154.

**Comment by GinIsTheAnswer** [comment]
> Had this issue trying to resume training on a model as well. Got training working again by applying this monkey patch in `feature_networks/vit.py` (in a similar fashion to how it's already being done in the `_make_*_backbone` functions).
> 
> ```python
> # Monkeypatching the VisionTransformer class to make it work when resuming training
> from timm.models.vision_transformer import VisionTransformer
> VisionTransformer.forward_flex = types.MethodType(forward_flex, VisionTransformer)
> VisionTransformer._resize_pos_embed = types.MethodType(_resize_pos_embed, VisionTransformer)
> ```
> 
> I added this just after the def of `forward_flex`, around line 154.

Worked for me. Perhaps this should be tidied up and made into a pull request?

**Comment by xiaoiker** [comment]
> ```python
> forward_flex 
> ```

Can I ask where to add these lines in this project?

**Comment by xiaoiker** [comment]
https://github.com/autonomousvision/stylegan_xl/issues/55#issuecomment-1163777456

Can I ask where to add these lines in this project?
