### ISSUE TITLE
KeyError: FullyConnectedLayer

### ISSUE THREAD

**Issue by JHendel-codes** [autonomousvision/stylegan_xl#57]
Does anyone know what this error is about? 
KeyError                                  Traceback (most recent call last)
Input In [19], in <cell line: 16>()
     14 fetch_model(network_url[Model])
     16 with dnnlib.util.open_url(network_name) as f:
---> 17     G = legacy.load_network_pkl(f)['G_ema'].to(device) # type: ignore
     20 zs = torch.randn([10000, G.mapping.z_dim], device=device)
     21 cs = torch.zeros([10000, G.mapping.c_dim], device=device)

File /workspace/./stylegan_xl/legacy.py:25, in load_network_pkl(f, force_fp16)
     24 def load_network_pkl(f, force_fp16=False):
---> 25     data = _LegacyUnpickler(f).load()
     27     # Legacy TensorFlow pickle => convert.
     28     if isinstance(data, tuple) and len(data) == 3 and all(isinstance(net, _TFNetworkStub) for net in data):

File /workspace/./stylegan_xl/torch_utils/persistence.py:193, in _reconstruct_persistent_obj(meta)
    190 module = _src_to_module(meta.module_src)
    192 assert meta.type == 'class'
--> 193 orig_class = module.__dict__[meta.class_name]
    194 decorator_class = persistent_class(orig_class)
    195 obj = decorator_class.__new__(decorator_class)

KeyError: 'FullyConnectedLayer'

**Comment by woctezuma** [comment]
> Does anyone know what this error is about?

Hard to say without knowing which pkl you are trying to import.

**Comment by JHendel-codes** [comment]
I tried it with the Imagenet and FFHQ defaults

**Comment by xl-sr** [comment]
What exactly is your setup? When cloning this repo and running eg. ```gen_images.py``` it works just fine.

**Comment by xl-sr** [comment]
inactive, closing issue for now

**Comment by kierancarrigg** [comment]
I get this same KeyError when attempting to load in the imagenet pkl. I also get this error when cloning the repo and running `gen_images.py`.

I'm running on Google Colab, maybe there is a version issue there somehow?

```Loading networks from "imagenet1024.pkl"...
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[/content/stylegan_xl/gen_images.py](https://localhost:8080/#) in <module>
    122 
    123 if __name__ == "__main__":
--> 124     generate_images() # pylint: disable=no-value-for-parameter
    125 
    126 #----------------------------------------------------------------------------

6 frames
[/usr/local/lib/python3.7/dist-packages/click/core.py](https://localhost:8080/#) in __call__(self, *args, **kwargs)
    827     def __call__(self, *args, **kwargs):
    828         """Alias for :meth:`main`."""
--> 829         return self.main(*args, **kwargs)
    830 
    831 

[/usr/local/lib/python3.7/dist-packages/click/core.py](https://localhost:8080/#) in main(self, args, prog_name, complete_var, standalone_mode, **extra)
    780             try:
    781                 with self.make_context(prog_name, args, **extra) as ctx:
--> 782                     rv = self.invoke(ctx)
    783                     if not standalone_mode:
    784                         return rv

[/usr/local/lib/python3.7/dist-packages/click/core.py](https://localhost:8080/#) in invoke(self, ctx)
   1064         _maybe_show_deprecated_notice(self)
   1065         if self.callback is not None:
-> 1066             return ctx.invoke(self.callback, **ctx.params)
   1067 
   1068 

[/usr/local/lib/python3.7/dist-packages/click/core.py](https://localhost:8080/#) in invoke(*args, **kwargs)
    608         with augment_usage_errors(self):
    609             with ctx:
--> 610                 return callback(*args, **kwargs)
    611 
    612     def forward(*args, **kwargs):  # noqa: B902

[/content/stylegan_xl/gen_images.py](https://localhost:8080/#) in generate_images(network_pkl, seeds, batch_sz, truncation_psi, centroids_path, noise_mode, outdir, translate, rotate, class_idx)
     96     device = torch.device('cuda')
     97     with dnnlib.util.open_url(network_pkl) as f:
---> 98         G = legacy.load_network_pkl(f)['G_ema']
     99         G = G.eval().requires_grad_(False).to(device)
    100 

[/content/stylegan_xl/legacy.py](https://localhost:8080/#) in load_network_pkl(f, force_fp16)
     23 
     24 def load_network_pkl(f, force_fp16=False):
---> 25     data = _LegacyUnpickler(f).load()
     26 
     27     # Legacy TensorFlow pickle => convert.

[/content/torch_utils/persistence.py](https://localhost:8080/#) in _reconstruct_persistent_obj(meta)
    191 
    192     assert meta.type == 'class'
--> 193     orig_class = module.__dict__[meta.class_name]
    194     decorator_class = persistent_class(orig_class)
    195     obj = decorator_class.__new__(decorator_class)

KeyError: 'FullyConnectedLayer'
