### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable in Discriminator

### ISSUE THREAD

**Issue by Booooooooooo** [autonomousvision/stylegan_xl#60]
I am trying to use the discriminator in imagenet512.pkl
This is how I load it:
```
network_pkl = config['network_pkl']
print(network_pkl)
with dnnlib.util.open_url(network_pkl) as f:
    module = legacy.load_network_pkl(f)
    G = module['G_ema']
    discriminator = module['D']
    G = G.eval().requires_grad_(False).to(device)
```

then:
```
class_indices = torch.full((real_img.shape[0],), config['image_class_idx']).cuda()
c = F.one_hot(class_indices, G.c_dim)
recon_pred = discriminator(recon_img, c)
```

However, I got
```
File "/apdcephfs/private_v_boooowang/liif/pg_modules/discriminator.py", line 203, in forward
    x_n = Normalize(feat.normstats['mean'], feat.normstats['std'])(x)
TypeError: 'NoneType' object is not subscriptable
```
What is the problem? Please help me with it. Thank you so much.

**Comment by xl-sr** [comment]
Mhm, hard to say. Can you check what feat.normstats contains?

**Comment by xl-sr** [comment]
inactive, closing issue for now

**Comment by Booooooooooo** [comment]
I con't know what feat.normstats contains.... It is in https://github.com/autonomousvision/stylegan_xl/blob/4241ff9cfeb69d617427107a75d69e9d1c2d92f2/pg_modules/discriminator.py#L207
When using stylegan3-t-ffhq-1024x1024.pkl, this problem does not occur. However, if using the pkl file download from the link you provide, I will get this problem.

**Comment by convexalpha** [comment]
Facing the same error for imagenet256.pkl

**Comment by vihaanmisra** [comment]
Facing the same error for imagenet256.pkl
