### ISSUE TITLE
CUDA Errors

### ISSUE THREAD

**Issue by abhay-sheshadri** [autonomousvision/stylegan_xl#62]
I keep receiving some CUDA errors at random times during training.  The errors that I get are usually the following:
```
RuntimeError: CUDA error: misaligned address
```
```
RuntimeError: CUDA error: an illegal memory access was encountered
```

I am using Pytorch=1.9.1 with CudaToolkit 1.11.1 so I am unsure what the issue is?

**Comment by xl-sr** [comment]
this does not give me enough information, could you post your full log here?
