### ISSUE TITLE
How can I mix two real images to generate a mixed image by stylegan_xl?

### ISSUE THREAD

**Issue by 1170300714** [autonomousvision/stylegan_xl#69]
Thank!

**Comment by woctezuma** [comment]
Just as with any StyleGAN, I would guess.

For StyleGAN2, check `morphing` and `style transfer` at [`woctezuma/stylegan2-projecting-images`][proj-img].

[proj-img]: <https://github.com/woctezuma/stylegan2-projecting-images>

**Comment by 1170300714** [comment]
收到，感谢您的来件

**Comment by 1170300714** [comment]
thanks a lot




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月23日(星期四) 下午3:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [autonomousvision/stylegan_xl] How can I mix two real images to generate a mixed image by stylegan_xl? (Issue #69)





 
Just as with any StyleGAN, I would guess. For StyleGAN2, check morphing and style transfer at woctezuma/stylegan2-projecting-images.
