### ISSUE TITLE
Extra ')' in feature_networks/pretrained_builder.py

### ISSUE THREAD

**Issue by marianobasti** [autonomousvision/stylegan_xl#7]
On line 409, where it says 

`pretrained.CHANNELS, pretrained.RES_MULT = calc_dims(pretrained, is_vit=backbone in VITS) )`

should be

`pretrained.CHANNELS, pretrained.RES_MULT = calc_dims(pretrained, is_vit=backbone in VITS)`

**Comment by xl-sr** [comment]
fixed, thanks :)
