### ISSUE TITLE
imagenet

### ISSUE THREAD

**Issue by Youzebin** [autonomousvision/stylegan_xl#72]
Can you provide the code to handle Imagenet? Why do you mainly test imagenet but do not provide code to process imagenet data? 
I have some confusion in processing Imagenet, for example, there are some grayscale images in Imagenet, and when I use dataset_tool, it will report an error, should I change the grayscale images to RGB images in this case? Expecting to read 65536 bytes but only got 1078. skipping tag 3.
Does anyone have access to imagenet?

**Comment by woctezuma** [comment]
Related:
- #40
- #43 
- #67
